### ISSUE TITLE
Webpackify the project

### ISSUE THREAD

**Issue by j0n3lson** [mellychat/webapp#99]
See the discussion in #91 for motivations. This issue tracks the webpackification project. Roughly speaking there are 3 phases:

**Phase 1: Bundle all the things:** The goal is to produce a single global bundle that contains all dependencies. This will reduce the imports duplication and boilerplate in the pages. Bundling into one file closely mimics what we do today where we import every script/asset regardless of whether it's used in the page
- [x] All major dependencies are added (jquery, bootstrap etc)
- [ ] Per-page js dependencies are added
- [ ] Per-page css dependencies are added
- [ ] Per-page image dependencies are added

------

**Phase 2: Code Splitting:** The goal is to split the bundles into smaller bundles that include the per-page js and any dependencies they need. We will eliminate unnecessary imports in this phase. For example, owl.carousel is university imported despite only being used in the index page.

- [ ] Map dependencies to pages
- [ ] Bundle dependencies into per-page bundles
------

**Phase 3: Optimization:** There are several problems to solve in this phase

1. Common Dependencies are deplicated: At this point, we're bundling all assets into smaller bundles but they still may be pretty heavy to load since the code-split bundles contain all the dependencies. For example if `pageA.html` imports `bundle.a.js` which needs `dependencyA` then `dependencyA` is actually statically included in `bundle.a.js` making the file bigger. Additionally if some other file `bundle.b.js` also needs `dependencyA` then it too has it's own copy of `dependenyA`.  We can use `webpack.CommonsChunkPlugin` to get around this. We can also use it for common bits of our own js (e.g. `navBar.js`).
2. Split out External dependencies: Most major dependencies are hosted. We can instruct webpack to include them in the bundle but fetch them from the hosted CDN when loaded. 

- [ ] Split out common chunks that can be reused
- [ ] Split out external dependencies so that they are downloaded from CDN instead of packaged in the bundle.

------
